"""init

Revision ID: fbce173913d8
Revises: 
Create Date: 2026-07-01 12:19:44.522571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbce173913d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('chekk_wallet_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('insurance_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sa.Enum('student', 'supervisor', 'admin', 'patient', name='userrole'), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('matric_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('hospital', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('mdcn_reg_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.Enum('encounter_complete', 'encounter_approved', 'encounter_rejected', 'wallet_push', 'credit_earned', 'skill_triggered', name='activitytype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'pending_review', 'finalized', 'rejected', name='encounterstatus'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe', 'life_threatening', name='severity'), nullable=True),
    sa.Column('associated_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consent_obtained', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ai_diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_differential', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_actions_triggered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('student_pre_ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('student_pre_ai_timestamp', sa.DateTime(), nullable=True),
    sa.Column('vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exam_notes', sa.Text(), nullable=True),
    sa.Column('working_diagnosis', sa.Text(), nullable=True),
    sa.Column('investigations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('follow_up', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('supervisor_notes', sa.Text(), nullable=True),
    sa.Column('supervisor_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('credits_provisional', sa.Integer(), nullable=False),
    sa.Column('credits_earned', sa.Integer(), nullable=False),
    sa.Column('credit_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_status'), 'encounters', ['status'], unique=False)
    op.create_index(op.f('ix_encounters_student_id'), 'encounters', ['student_id'], unique=False)
    op.create_table('action_skill_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_skill_logs_encounter_id'), 'action_skill_logs', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_action_skill_logs_skill_name'), 'action_skill_logs', ['skill_name'], unique=False)
    op.create_table('clinical_credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('history_taking', 'physical_exam', 'diagnosis', 'treatment', 'communication', name='creditcategory'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('signed_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_credits_encounter_id'), 'clinical_credits', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_clinical_credits_student_id'), 'clinical_credits', ['student_id'], unique=False)
    op.create_table('wallet_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('chekk_record_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qr_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encryption_iv', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'pushed', 'accessed', 'expired', name='walletrecordstatus'), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id')
    )
    op.create_index(op.f('ix_wallet_records_patient_id'), 'wallet_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_wallet_records_status'), 'wallet_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_records_status'), table_name='wallet_records')
    op.drop_index(op.f('ix_wallet_records_patient_id'), table_name='wallet_records')
    op.drop_table('wallet_records')
    op.drop_index(op.f('ix_clinical_credits_student_id'), table_name='clinical_credits')
    op.drop_index(op.f('ix_clinical_credits_encounter_id'), table_name='clinical_credits')
    op.drop_table('clinical_credits')
    op.drop_index(op.f('ix_action_skill_logs_skill_name'), table_name='action_skill_logs')
    op.drop_index(op.f('ix_action_skill_logs_encounter_id'), table_name='action_skill_logs')
    op.drop_table('action_skill_logs')
    op.drop_index(op.f('ix_encounters_student_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_status'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
